<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<style>
body {
	width: 100%;
	margin: 0px;
	padding: 0px;
	font-family: Tahoma, Geneva, sans-serif;
	font-size: 12px;
}

.container {
	width: 580px;
	margin: auto;
	width: 580px;
	margin: auto;
	border: 1px solid #e2e2e2;
}

.header {
	height: 91px;
	background: #a9b6c8; /* Old browsers */
	background: -moz-linear-gradient(top, #a9b6c8 0%, #7b8fab 100%);
	/* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #a9b6c8),
		color-stop(100%, #7b8fab)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top, #a9b6c8 0%, #7b8fab 100%);
	/* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top, #a9b6c8 0%, #7b8fab 100%);
	/* Opera 11.10+ */
	background: -ms-linear-gradient(top, #a9b6c8 0%, #7b8fab 100%);
	/* IE10+ */
	background: linear-gradient(to bottom, #a9b6c8 0%, #7b8fab 100%);
	/* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#a9b6c8',
		endColorstr='#7b8fab', GradientType=0); /* IE6-9 */
}

.footer p {
	text-align: center;
	line-height: 43px;
}

.footer {
	background: #45484d; /* Old browsers */
	background: -moz-linear-gradient(top, #45484d 0%, #000000 100%);
	/* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #45484d),
		color-stop(100%, #000000)); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top, #45484d 0%, #000000 100%);
	/* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top, #45484d 0%, #000000 100%);
	/* Opera 11.10+ */
	background: -ms-linear-gradient(top, #45484d 0%, #000000 100%);
	/* IE10+ */
	background: linear-gradient(to bottom, #45484d 0%, #000000 100%);
	/* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#45484d',
		endColorstr='#000000', GradientType=0); /* IE6-9 */
	height: 48px;
	color: #fff;
}

.content {
	border: 1px solid #959595;
	padding: 5px;
	margin: 5px;
	color: #666666;
}

.content h2 {
	font-size: 12px;
}

.content p {
	margin: 33px 0px;
	line-height: 18px;
}

.content p a {
	color: #3364d4;
}

.tab {
	margin-left: 40px;
}
</style>
</head>

<body>
	<?php
	use Application\Model\MemreasConstants;
	?>
<div class="container">
		<div class="header" style="height: 91px; background: #a9b6c8;">
			<img
				src="<?php echo MemreasConstants::ORIGINAL_URL?>memreas/img/logo.png"
				width="288" height="72" />
		</div>
		<div class="content">
			<h2>To <?php echo $receiver_name?>,</h2>
			<br>

				<p>Welcome to memreas!</p>
				<p class="tab">
					You have been flagged in DMCA violation for the following media: 
                                        <img src="<?php echo $mediaUrl?>" width="288" height="72" />
  

Per DMCA rules you have 14 days to file a counter claim.  You may use the DMCA section of the more tab to file your counter claim.  Your counter notice must include the following:<br />
 - Signed written communication identifying the material removed and the location of the material prior to removal<br />
 - A statement under penalty of perjury that you (aka - username) has a good faith belief that the material was removed as a removed as a result of a mistake or misidentification.<br />
 - Provide your name, address, and email address<br />
 - Statement that you (aka username) will accept service of process and consents to the jurisdiction of Federal District Court.<br />

A form is available unders the more section of www.memreas.com where you should find your violation notice data and can counter claim.<br />

In the event you counter claim, memreas will provide you with the reporter's email address such that you and the reporter can resolve the reported violation.<br />

Please be aware that memreas does not engage any further in the process.  In the event that you have resolved the issue with the reporter you are free to delete the material and upload your copyrighted material.<br />

Regards,<br />
memreas team<br />

					<a href="<?php echo $email_verification_url?>">Media</a><br />
				</p>

				<p>
					Best Regards,<br /> <img
						src="<?php echo MemreasConstants::ORIGINAL_URL?>memreas/img/footer_ref.png"
						width="103" height="20" />
				</p>
		
		</div>
		<div class="footer" style="background: #45484d;">
			<p><?php echo MemreasConstants::COPYRIGHT?></p>
		</div>
	</div>
</body>
</html>
