<?php
/**
 * Copyright (C) 2015 memreas llc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */
use Application\Model\MemreasConstants;

$user_id = $this->user_id;
$username = $this->username;
// echo "user_id ----> " . $user_id;
// echo "<p>";
echo "Welcome to Stripe Services" . PHP_EOL;
echo "whoami ----> " . $username . " : " . $user_id;

?>
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>memreas</title>
<link rel="stylesheet"
	href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

<!--jQuery Lybrary-->
<script src="/memreas/js/jquery.js"></script>

<script type="text/javascript">

//Test stripe services using proxy
<?php
echo "var proxy_url = '" . MemreasConstants::ORIGINAL_URL . "?action=';";
?>

function getCookie(cname) {
    var name = cname + "=";
    var ca = document.cookie.split(';');
    for(var i=0; i<ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1);
        if (c.indexOf(name) == 0) return c.substring(name.length,c.length);
    }
    return "";
}
var user_id;
var username;
var sid;
var memreascookie;

/*
 * 
 * stripe_ actions...
 * accounthistoryAction()
 * activeCreditAction()
 * addSellerAction()
 * addValueAction()
 * buyMediaAction()
 * checkOwnEventAction()
 * deleteCardsAction()
 * decrementAction()
 * getCustomerInfoAction()
 * getUserBalanceAction()
 * listPlanAction()
 * listCardsAction()
 * listMassPayeeAction()
 * storeCardAction()
 * subscribeAction()
 * viewCardAction()
 * updateCardAction()
 */

 console.log("cookies" + document.cookie);
	
/////////////////////
// Store Card
/////////////////////
var doStripeStoreCard = function () {

	var action = "stripe_storeCard";
	var obj = new Object();
	obj.sid = getCookie("PHPSESSID");
    obj.user_id = user_id;
	obj.first_name = $("#first_name").val();
	obj.last_name = $("#last_name").val();
	obj.credit_card_type = $("#credit_card_type").val();
	obj.credit_card_number = $("#credit_card_number").val();
	obj.expiration_month = $("#expiration_month").val();
	obj.expiration_year = $("#expiration_year").val();
	obj.cvc = $("#cvc").val();
	obj.address_line_1 = $("#address_line_1").val();
	obj.address_line_2 = $("#address_line_2").val();
	obj.city = $("#city").val();
	obj.state = $("#state").val();
	obj.zip_code = $("#zip_code").val();
    var jsonStoreCard = JSON.stringify(obj);
    var data = "";

    data = '{"action": "' + action + '", ' +
    '"type":"jsonp", ' +
    '"json": ' + jsonStoreCard  +
    '}';

	//var results += json_paypalStoreCard;
	$("#results").val(jsonStoreCard, null, '\t');

	$.ajax( {
	  type:'post',
	  url: proxy_url + action,
	  dataType: 'jsonp',
	  data: 'json=' + data,
	  success: function(json){
	  	var req_resp = $("#results").val() + "\n\n" + JSON.stringify(json, null, '\t');
	  	$("#results").val(req_resp);
	  },
	  error: function (jqXHR, textStatus, errorThrown) {
	  	//alert("Inside error jqXHR...");
       	alert(jqXHR.responseText);
       	alert(jqXHR.status);
	    	//alert(textStatus);
       	//alert(errorThrown);
	  }
	});
	return false;
}


/////////////////////
//List Cards
/////////////////////
var doListCards = function (element, list) {

	var action = "stripe_listCards";
	var obj = new Object();
	obj.sid = getCookie("PHPSESSID");
 	obj.user_id = user_id;
 var jsonStoreCard = JSON.stringify(obj);
 var data = "";

 data = '{"action": "' + action + '", ' +
 '"type":"jsonp", ' +
 '"json": ' + jsonStoreCard  +
 '}';

	//var results += json_paypalStoreCard;
	$("#results").val(jsonStoreCard, null, '\t');

	$.ajax( {
	  type:'post',
	  url: proxy_url + action,
	  dataType: 'jsonp',
	  data: 'json=' + data,
	  success: function(json){
		  	var req_resp = $(element).val() + "\n\n" + JSON.stringify(json, null, '\t');
		  	var html_str = "";
		  	var html_button = "";
		  	$(element).val(req_resp);
		  	if (json.status == "Success") {
		  		for (var i=0;i<json.payment_methods.length;i++)
				{
					html_str +=
							'<tr>' +
							'<td><input type="radio" onclick="onRadioCardListforSubscribeSelected(this);" id="card_selected_' + i + '" name="card_selected" value="'+ i + '">' +
							//'<td>user_id' +
							//'<td><input type="text" id="user_id" name="user id" value="'+ json.payment_methods[i].user_id + '">' +
							'<td>stripe ref id:' +
							'<td><input type="text" class="card_numbers" id="stripe_card_reference_id_' + i + '" name="stripe_card_reference_id_' + i + '" value="'+ json.payment_methods[i].stripe_card_reference_id + '">' +
							'<td>card type:' +
							'<td><input type="text" id="card_type_' + i + '" name="card_type_' + i + '" value="'+ json.payment_methods[i].card_type + '">' +
							'<td>card number' +
							'<td><input type="text" id="card_number_' + i + '" name="card_number_' + i + '" value="'+ json.payment_methods[i].obfuscated_card_number + '">' +
							'</tr><tr>' +
							'<td>' +
							'<td>first name:' +
							'<td><input type="text" id="first_name_' + i + '" name="first_name_' + i + '" value="'+ json.payment_methods[i].first_name + '">' +
							'<td>last name' +
							'<td><input type="text" id="last_name_' + i + '" name="last_name_' + i + '" value="'+ json.payment_methods[i].last_name + '">' +
							'<td>address line 1:' +
							'<td><input type="text" id="address_line_1_' + i + '" name="address_line_1_' + i + '" value="'+ json.payment_methods[i].address_line_1 + '">' +
							'<td>address line 2:' +
							'<td><input type="text" id="address_line_2_' + i + '" name="address_line_2_' + i + '" value="'+ json.payment_methods[i].address_line_2 + '">' +
							'<td>city:' +
							'<td><input type="text" id="city_' + i + '" name="city_' + i + '" value="'+ json.payment_methods[i].city + '">' +
							'<td>state:' +
							'<td><input type="text" id="state_' + i + '" name="state_' + i + '" value="'+ json.payment_methods[i].state + '">' +
							'<td>zip code:' +
							'<td><input type="text" id="zip_code_' + i + '" name="zip_code_' + i + '" value="'+ json.payment_methods[i].zip_code + '">' +
							'</tr>';
				}
		  		$(list).html(html_str);
		  	}
		  	return true;
		  },
		  error: function (jqXHR, textStatus, errorThrown) {
	       	alert(jqXHR.responseText);
	       	alert(jqXHR.status);
	    		//alert(textStatus);
	       	//alert(errorThrown);
		  }
	});
	return false;
}

/////////////////////
//Delete Cards
/////////////////////
doDeleteCards = function () {

	//Fetch the list of cards to delete...
	var selected = new Array();
	$("input[name=card_selected]:checked").each(function() {
     card_number = $(this).parents("tr").find('input.card_numbers').val();
	    selected.push(card_number);
	});

	if(selected.length == 0) {
		alert("No cards checked to delete");
		return;
	}

 var jsonDeleteCards = JSON.stringify(selected, null, '\t');
 var data = "";
 var result = "";

 //if () {}
 data = '{"action": "delete", ' +
 '"type":"jsonp", ' +
 '"json": ' + jsonDeleteCards  +
 '}';

	$("#list_delete_cards_results").val(jsonDeleteCards);

	$.ajax( {
	  type:'post',
	  url: stripeDeleteCards_url,
	  dataType: 'jsonp',
	  data: 'json=' + data,
	  success: function(json){
	  	var req_resp = $("#list_delete_cards_results").val() + "\n\n" + JSON.stringify(json, null, '\t');
	  	$("#list_delete_cards_results").val(req_resp);
	  	return true;
	  },
	  error: function (jqXHR, textStatus, errorThrown) {
    		alert(jqXHR.responseText);
    		alert(jqXHR.status);
	 	//alert(textStatus);
	    	//alert(errorThrown);
	  }
	});
	return false;
}


/////////////////////
//- Login
/////////////////////
var doLogin = function () {
	var action = 'login';
	var user = new Object;
	user.username = $("#username").val();
	user.password = $("#password").val();
	var xml = new Object();
	xml.xml = "<xml><login><username>" + user.username + 
	"</username>" + "<password>" + user.password + "</password>" + 
	"<device_type>web</device_type><device_id>127.0.0.1</device_id></login></xml>";
	var obj = new Object();
	obj.action = action;
	obj.type = "jsonp";
	obj.json = xml;
	var data = JSON.stringify(obj);
	var response;
	
	$.ajax( {
		  type:'post',
		  url: proxy_url + action,
		  dataType: 'jsonp',
		  data: 'json=' + data,
		  success: function(response){
			  console.log("response xml --->"+response.data);
		  	var req_resp = $("#login_results").val() + "\n\n" + JSON.stringify(response, null, '\t');
		  	$("#login_results").val(req_resp);

			//parse xml
			var xml = response.data,
  			xmlDoc = $.parseXML( xml ),
  			$xml = $( xmlDoc ),
  			$user_id = $xml.find( "user_id" );
			
			xml = response.data,
  			xmlDoc = $.parseXML( xml ),
  			$xml = $( xmlDoc ),
  			$username = $xml.find( "username" );
  			

			xml = response.data,
  			xmlDoc = $.parseXML( xml ),
  			$xml = $( xmlDoc ),
  			$sid = $xml.find( "sid" );

			
			user_id =  $user_id.text();
			username =  $username.text();
			sid =  $sid.text();
			console.log("user_id---->" + $user_id.text());
			console.log("username---->" + $username.text());
			console.log("sid---->" + $sid.text());

		  	
		  },
		  error: function (jqXHR, textStatus, errorThrown) {
		  	//alert("Inside error jqXHR...");
		    	alert(jqXHR.responseText);
		    	alert(jqXHR.status);
	 		//alert(textStatus);
		    	//alert(errorThrown);
		  }
		});
}

</script>

<!-- JQuery -->
<script
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="/memreas/js/modernizr.custom.17475.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!--Bootstrap jQuery-->
<script src="/memreas/js/bootstrap.min.js"></script>

<!-- Fetch the user_id -->
<script type="text/javascript">
	var user_id = "<?php echo $user_id; ?>";
	var json;

	//Login
    $(document).ready(function () {
        $("#btnOK9").click(onLoginCallClicked);
    });
    function onLoginCallClicked() {
        doLogin();
    }
	
	//Store Card
    $(document).ready(function () {
        $("#btnOK").click(onStoreCardCallClicked);
    });
    function onStoreCardCallClicked() {
        doStripeStoreCard();
    }

	//List Card(s)
    $(document).ready(function () {
        $("#btnOK2").click(onListCardsCallClicked);
    });
    function onListCardsCallClicked() {
    		doListCards('#list_delete_cards_results', '#card_list');
    }
    
	//Delete Card(s)
    $(document).ready(function () {
        $("#btnDelete").click(onBtnDeleteCallClicked);
    });
    function onBtnDeleteCallClicked() {
        jQuery.paypalDeleteCards();
    }
    /*
    //List Cards Picker for Add Value
    $(document).ready(function () {
        $("#btnOK4").click(onListCardsForAddValueCallClicked);
    });
    function onListCardsForAddValueCallClicked() {
    		doListCards('#add_value_results', '#card_list4');
    }
    
	//Add Value
    $(document).ready(function () {
        $("#btnAddValue4").click(onBtnAddValue4CallClicked);
    });
    function onBtnAddValue4CallClicked() {
        jQuery.paypalAddValue('#add_value_results');
    }
    
	//Decrement Value
    $(document).ready(function () {
        $("#btnDecrementValue5").click(onBtnDecrementValue5CallClicked);
    });
    function onBtnDecrementValue5CallClicked() {
        jQuery.paypalDecrementValue('#decrement_value_results');
    }

	//Account History
    $(document).ready(function () {
        $("#btnAccountHistory6").click(onBtnAccountHistoryCallClicked);
    });
    function onBtnAccountHistoryCallClicked() {
        jQuery.paypalAccountHistory('#account_history_results');
    }

	//Add Seller
    $(document).ready(function () {
        $("#btnOK3").click(onBtn3CallClicked);
    });
    function onBtn3CallClicked() {
        jQuery.paypalAddSeller();
    }

	//List MassPayees
    $(document).ready(function () {
        $("#btnOK7").click(onBtn7CallClicked);
    });
    function onBtn7CallClicked() {
        jQuery.paypalListMassPayees('#mass_pay_results', '#mass_pay_list');
    }

	//Payout MassPayees
    $(document).ready(function () {
        $("#btnPayOut7").click(onBtnPayOut7CallClicked);
    });
    function onBtnPayOut7CallClicked() {
        jQuery.paypalPayoutMassPayees('#mass_pay_results', '#mass_pay_list');
    }

	//Create and Manage Subscription
	//List Card(s)
    $(document).ready(function () {
        $("#btnListCardsForSubscribe").click(onBtnListCardsForSubscribeCallClicked);
    });
    function onBtnListCardsForSubscribeCallClicked() {
        jQuery.paypalListCards('#subscribe_results', '#subscribe_card_list');
    }
	//Create/Update subscription
	$(document).ready(function () {
        $("#btnSubscribe").click(onBtnSubscribeCallClicked);
    });
    function onBtnSubscribeCallClicked() {
        jQuery.payPalSubscribe('#subscribe_results');
    }

	//Update address based on selection
    $(document).ready(function () {
        $("#card_selected").change(onRadioCardListforSubscribeSelected);
	});

    function onRadioCardListforSubscribeSelected(myRadio) {
        var i = myRadio.value;
        $('#subscribe_first_name').val($('#first_name_'+i).val());
        $('#subscribe_last_name').val($('#last_name_'+i).val());
        $('#subscribe_address_line_1').val($('#address_line_1_'+i).val());
        $('#subscribe_address_line_2').val($('#address_line_2_'+i).val());
        $('#subscribe_city').val($('#city_'+i).val());
        $('#subscribe_state').val($('#state_'+i).val());
        $('#subscribe_zip_code').val($('#zip_code_'+i).val());
	}
	*/
	
    $(function() {
	    $( "#tabs" ).tabs();
	});
	
	//DatePicker...
	$(function() {
	    $( "#dteFrom" ).datepicker();
	    var dt = new Date();
	    dt.setMonth(dt.getMonth()-1)
		$( "#dteFrom" ).datepicker('setDate', dt);	    
	});	
	
	$(function() {
	    $( "#dteTo" ).datepicker();
		$( "#dteTo" ).datepicker('setDate', new Date());	    
	});	
</script>
</head>
<body>

	<input type="hidden" name="user_id" value="<?php echo $user_id; ?>" />
	<div id="tabs">
		<ul>
			<li><a href="#tabs-1">Store Card</a></li>
			<li><a href="#tabs-2">List and Delete Cards</a></li>
			<li><a href="#tabs-3">Add a Seller</a></li>
			<li><a href="#tabs-4">Add Value to Account</a></li>
			<li><a href="#tabs-5">Decrement Account</a></li>
			<li><a href="#tabs-6">Account History</a></li>
			<li><a href="#tabs-7">MassPay</a></li>
			<li><a href="#tabs-8">Subscriptions</a></li>
			<li><a href="#tabs-9">Login</a></li>
		</ul>
		<div id="tabs-1">
			<form id="store_card_form" name=store_card_form " action="#">
				<table>
					<tr>
						<td>first name:
						
						<td><input type="text" id="first_name" name="first_name"
							value="John">
						
						<td>last name:
						
						<td><input type="text" id="last_name" name="last_name"
							value="Meah">
					
					</tr>
					<tr>
						<td>address line 1:
						
						<td><input type="text" id="address_line_1" name="address_line_1"
							value="125 Bowery Street">
						
						<td>credit card #:
						
						<td><select id="credit_card_type" name="credit_card_type"
							onChange="javascript:generateCC(); return false;">
								<option value="Visa" selected="selected">Visa</option>
								<option value="MasterCard">MasterCard</option>
								<option value="Discover">Discover</option>
								<option value="Amex">American Express</option>
						</select>
					
					</tr>
					<tr>
						<td>address line 2:
						
						<td><input type="text" id="address_line_2" name="address_line_2"
							value="Suite 814">
						
						<td>credit card #:
						
						<td><input type="text" id="credit_card_number"
							name="credit_card_number">
					
					</tr>
					<tr>
						<td>city:
						
						<td><input type="text" id="city" name="city" value="New York">
						
						<td>expiration date:
						
						<td><select id="expiration_month" name="expiration_month">
								<option value="01">01</option>
								<option value="02">02</option>
								<option value="03">03</option>
								<option value="04">04</option>
								<option value="05">05</option>
								<option value="06" selected>06</option>
								<option value="07">07</option>
								<option value="08">08</option>
								<option value="09">09</option>
								<option value="10">10</option>
								<option value="11">11</option>
								<option value="12">12</option>
						</select> <select id="expiration_year" name="expiration_year">
								<option value="2016">2016</option>
								<option value="2017" selected>2017</option>
								<option value="2018">2018</option>
								<option value="2019">2019</option>
								<option value="2020">2020</option>
						</select>
					
					</tr>
					<tr>
						<td>CVC</td>
						<td><input id="cvc" type="text" name="cvc" value="317" /></td>
					</tr>
					<tr>
						<td>state:
						
						<td><select id=state name="state">
								<option value=""></option>
								<option value="AK">AK</option>
								<option value="AL">AL</option>
								<option value="AR">AR</option>
								<option value="AZ">AZ</option>
								<option value="CA" selected>CA</option>
								<option value="CO">CO</option>
								<option value="CT">CT</option>
								<option value="DC">DC</option>
								<option value="DE">DE</option>
								<option value="FL">FL</option>
								<option value="GA">GA</option>
								<option value="HI">HI</option>
								<option value="IA">IA</option>
								<option value="ID">ID</option>
								<option value="IL">IL</option>
								<option value="IN">IN</option>
								<option value="KS">KS</option>
								<option value="KY">KY</option>
								<option value="LA">LA</option>
								<option value="MA">MA</option>
								<option value="MD">MD</option>
								<option value="ME">ME</option>
								<option value="MI">MI</option>
								<option value="MN">MN</option>
								<option value="MO">MO</option>
								<option value="MS">MS</option>
								<option value="MT">MT</option>
								<option value="NC">NC</option>
								<option value="ND">ND</option>
								<option value="NE">NE</option>
								<option value="NH">NH</option>
								<option value="NJ">NJ</option>
								<option value="NM">NM</option>
								<option value="NV">NV</option>
								<option value="NY" selected>NY</option>
								<option value="OH">OH</option>
								<option value="OK">OK</option>
								<option value="OR">OR</option>
								<option value="PA">PA</option>
								<option value="RI">RI</option>
								<option value="SC">SC</option>
								<option value="SD">SD</option>
								<option value="TN">TN</option>
								<option value="TX">TX</option>
								<option value="UT">UT</option>
								<option value="VA">VA</option>
								<option value="VT">VT</option>
								<option value="WA">WA</option>
								<option value="WI">WI</option>
								<option value="WV">WV</option>
								<option value="WY">WY</option>
								<option value="AA">AA</option>
								<option value="AE">AE</option>
								<option value="AP">AP</option>
								<option value="AS">AS</option>
								<option value="FM">FM</option>
								<option value="GU">GU</option>
								<option value="MH">MH</option>
								<option value="MP">MP</option>
								<option value="PR">PR</option>
								<option value="PW">PW</option>
								<option value="VI">VI</option>
						</select>
						
						<td>
						
						<td>
					
					</tr>
					<tr>
						<td>zip:
						
						<td><input type="text" id="zip_code" name="zip_code" value="10018">
						
						<td>
						
						<td><input type="hidden" id="isValid" name="isValid" value="1">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnOK" type="button" name="ok" value="ok">
						
						<td>
						
						<td><input id="btnClear" type="button" name="clear" value="cancel">
					
					</tr>
				</table>
				<div id="store_card_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="results" name="results" rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>

		<div id="tabs-2">
			<form id="list_delete_cards_form" name=list_delete_cards_form
				" action="#">
				<table>
					<div id="card_list"></div>
					<tr>
						<td>
						
						<td><input id="btnOK2" type="button" name="ok" value="list cards">
						
						<td>
						
						<td><input id="btnDelete" type="button" name="delete"
							value="delete">
					
					</tr>
				</table>

				<div id="list_delete_cards_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="list_delete_cards_results"
									name="list_delete_cards_results" rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-3">
			<form id="add_seller_form" name=add_seller_form
				" action="/index/paypal">
				<table>
					<tr>
						<td>user name:
						
						<td><input type="text" id="add_seller_user_name"
							name="add_seller_user_name" value="jmeah2">
						
						<td>stripe email address:
						
						<td><input type="text" id="add_seller_paypal_email_address"
							name="add_seller_paypal_email_address"
							value="jmeah_seller@memreas.com">
					
					</tr>
					<tr>
						<td>first name:
						
						<td><input type="text" id="add_seller_first_name"
							name="add_seller_first_name" value="John">
						
						<td>last name:
						
						<td><input type="text" id="add_seller_last_name"
							name="add_seller_last_name" value="Meah">
					
					</tr>
					<tr>
						<td>address line 1:
						
						<td><input type="text" id="add_seller_address_line_1"
							name="add_seller_address_line_1" value="125 Bowery Street">
					
					</tr>
					<tr>
						<td>address line 2:
						
						<td><input type="text" id="add_seller_address_line_2"
							name="add_seller_address_line_2" value="Suite 814">
					
					</tr>
					<tr>
						<td>city:
						
						<td><input type="text" id="add_seller_city" name="add_seller_city"
							value="New York">
					
					</tr>
					<tr>
						<td>state:
						
						<td><select id="add_seller_state" name="add_seller_state">
								<option value=""></option>
								<option value="AK">AK</option>
								<option value="AL">AL</option>
								<option value="AR">AR</option>
								<option value="AZ">AZ</option>
								<option value="CA" selected>CA</option>
								<option value="CO">CO</option>
								<option value="CT">CT</option>
								<option value="DC">DC</option>
								<option value="DE">DE</option>
								<option value="FL">FL</option>
								<option value="GA">GA</option>
								<option value="HI">HI</option>
								<option value="IA">IA</option>
								<option value="ID">ID</option>
								<option value="IL">IL</option>
								<option value="IN">IN</option>
								<option value="KS">KS</option>
								<option value="KY">KY</option>
								<option value="LA">LA</option>
								<option value="MA">MA</option>
								<option value="MD">MD</option>
								<option value="ME">ME</option>
								<option value="MI">MI</option>
								<option value="MN">MN</option>
								<option value="MO">MO</option>
								<option value="MS">MS</option>
								<option value="MT">MT</option>
								<option value="NC">NC</option>
								<option value="ND">ND</option>
								<option value="NE">NE</option>
								<option value="NH">NH</option>
								<option value="NJ">NJ</option>
								<option value="NM">NM</option>
								<option value="NV">NV</option>
								<option value="NY" selected>NY</option>
								<option value="OH">OH</option>
								<option value="OK">OK</option>
								<option value="OR">OR</option>
								<option value="PA">PA</option>
								<option value="RI">RI</option>
								<option value="SC">SC</option>
								<option value="SD">SD</option>
								<option value="TN">TN</option>
								<option value="TX">TX</option>
								<option value="UT">UT</option>
								<option value="VA">VA</option>
								<option value="VT">VT</option>
								<option value="WA">WA</option>
								<option value="WI">WI</option>
								<option value="WV">WV</option>
								<option value="WY">WY</option>
								<option value="AA">AA</option>
								<option value="AE">AE</option>
								<option value="AP">AP</option>
								<option value="AS">AS</option>
								<option value="FM">FM</option>
								<option value="GU">GU</option>
								<option value="MH">MH</option>
								<option value="MP">MP</option>
								<option value="PR">PR</option>
								<option value="PW">PW</option>
								<option value="VI">VI</option>
						</select>
						
						<td>
						
						<td>
					
					</tr>
					<tr>
						<td>zip:
						
						<td><input type="text" id="add_seller_zip_code"
							name="add_seller_zip_code" value="10018">
						
						<td>
						
						<td><input type="hidden" id="isValid" name="isValid" value="1">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnOK3" type="button" name="ok" value="ok">
						
						<td>
						
						<td><input id="btnClear" type="button" name="clear" value="cancel">
					
					</tr>
				</table>
				<div id="add_seller_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="add_seller_form_results"
									name="add_seller_form_results" rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-4">
			<form id="add_value_form" name=add_value_form
				" action="/index/paypalAddValue">
				<table>
					<div id="card_list4"></div>
					<tr>
						<td>
						
						<td>$ amount(USD):
						
						<td>
						
						<td><input id="amount" type="text" name="amount" value="5">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnOK4" type="button" name="ok" value="list cards">
						
						<td>
						
						<td><input id="btnAddValue4" type="button" name="add_value"
							value="add value">
					
					</tr>
				</table>

				<div id="add_value_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="add_value_results" name="add_value_results"
									rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-5">
			<form id="decrement_value_form" name=decrement_value_form
				" action="/index/paypalAddValue">
				<table>
					<tr>
						<td>
						
						<td>Seller:
						
						<td>
						
						<td><input id="seller" type="text" name="seller" value="jmeah2">
					
					</tr>
					<tr>
						<td>
						
						<td>memreas_master:
						
						<td>
						
						<td><input id="memreas_master" type="text" name="memreas_master"
							value="jmeah3">
					
					</tr>
					<tr>
						<td>
						
						<td>$ amount(USD):
						
						<td>
						
						<td><input id="decrement_amount" type="text"
							name="decrement_amount" value=".25">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnDecrementValue5" type="button" name="ok"
							value="purchase">
					
					</tr>
				</table>

				<div id="decrement_value_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="decrement_value_results"
									name="decrement_value_results" rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-6">
			<form id="account_history_form" name=account_history_form
				" action="/index/paypalListDeleteCards">
				<table>
					<tr>
						<td>User Name:
						
						<td><input id="account_history_form_user_name" type="text"
							name="account_history_form_user_name" value="jmeah1">
					
					</tr>
					<!--
			<tr>
				<td>Date From:
				<td><input id="dteFrom" type="text" name="dteFrom" value="">
				<td>Date To:
				<td><input id="dteTo" type="text" name="dteTo" value="">
			</tr>
			-->
					<tr>
						<td>
						
						<td><input id="btnAccountHistory6" type="button" name="ok"
							value="get history">
					
					</tr>
				</table>

				<div id="account_history_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="account_history_results"
									name="account_history_results" rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-7">
			<form id="mass_pay_form" name=mass_pay_form
				" action="/index/payPalListMassPayee">
				<table>
					<div id="mass_pay_list"></div>
					<tr>
						<td>
						
						<td><input id="btnOK7" type="button" name="btnOK7"
							value="list mass payees">
						
						<td>
						
						<td><input id="btnPayOut7" type="button" name="btnPayOut7"
							value="payout">
					
					</tr>
				</table>

				<div id="mass_pay_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="mass_pay_results" name="mass_pay_results"
									rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-8">
			<form id="subscribe_form" name=subscribe_form
				" action="/index/paypal">
				<table>
					<div id="subscribe_card_list"></div>
					<tr>
						<td>plan:
						
						<td><select id=plan name="plan">
								<option value="PLAN_A_2GB_MONTHLY" selected>plan a: free for 2GB
									monthly</option>
								<option value="PLAN_B_10GB_MONTHLY">plan b: $2.95 for 10GB
									monthly</option>
								<option value="PLAN_C_50GB_MONTHLY">plan c: $4.95 for 50GB
									monthly</option>
								<option value="PLAN_D_100GB_MONTHLY">plan d: $9.95 for 100GB
									monthly</option>
						</select>
						
						<td>
						
						<td>
					
					</tr>
					<tr>
						<td>first name:
						
						<td><input type="text" id="subscribe_first_name"
							name="subscribe_first_name" value="Joe">
						
						<td>last name:
						
						<td><input type="text" id="subscribe_last_name"
							name="subscribe_last_name" value="Blake">
					
					</tr>
					<tr>
						<td>address line 1:
						
						<td><input type="text" id="subscribe_address_line_1"
							name="subscribe_address_line_1" value="900 Overbrook Drive">
						
						<td>Card Type#:
						
						<td><select id="subscribe_credit_card_type"
							name="subscribe_credit_card_type"
							onChange="javascript:generateCC(); return false;">
								<option value="Visa" selected="selected">Visa</option>
								<option value="MasterCard">MasterCard</option>
								<option value="Discover">Discover</option>
								<option value="Amex">American Express</option>
						</select>
					
					</tr>
					<tr>
						<td>address line 2:
						
						<td><input type="text" id="subscribe_address_line_2"
							name="subscribe_address_line_2" value="Suite 109">
						
						<td>credit card #:
						
						<td><input type="text" id="subscribe_credit_card_number"
							name="subscribe_credit_card_number">
					
					</tr>
					<tr>
						<td>city:
						
						<td><input type="text" id="subscribe_city" name="subscribe_city"
							value="New York">
						
						<td>expiration date:
						
						<td><select id="subscribe_expiration_month"
							name="subscribe_expiration_month">
								<option value="01">01</option>
								<option value="02">02</option>
								<option value="03">03</option>
								<option value="04">04</option>
								<option value="05">05</option>
								<option value="06">06</option>
								<option value="07">07</option>
								<option value="08 selected">08</option>
								<option value="09">09</option>
								<option value="10">10</option>
								<option value="11">11</option>
								<option value="12">12</option>
						</select> <select id="subscribe_expiration_year"
							name="subscribe_expiration_year">
								<option value="2013">2013</option>
								<option value="2014" selected>2014</option>
								<option value="2015">2015</option>
								<option value="2016">2016</option>
								<option value="2017">2017</option>
								<option value="2018">2018</option>
								<option value="2019">2019</option>
								<option value="2020">2020</option>
						</select>
					
					</tr>
					<tr>
						<td>CVC</td>
						<td><input type="text" name="cvc" value="111" /></td>
					</tr>
					<tr>
						<td>state:
						
						<td><select id=subscribe_state name="subscribe_state">
								<option value=""></option>
								<option value="AK">AK</option>
								<option value="AL">AL</option>
								<option value="AR">AR</option>
								<option value="AZ">AZ</option>
								<option value="CA" selected>CA</option>
								<option value="CO">CO</option>
								<option value="CT">CT</option>
								<option value="DC">DC</option>
								<option value="DE">DE</option>
								<option value="FL">FL</option>
								<option value="GA">GA</option>
								<option value="HI">HI</option>
								<option value="IA">IA</option>
								<option value="ID">ID</option>
								<option value="IL">IL</option>
								<option value="IN">IN</option>
								<option value="KS">KS</option>
								<option value="KY">KY</option>
								<option value="LA">LA</option>
								<option value="MA">MA</option>
								<option value="MD">MD</option>
								<option value="ME">ME</option>
								<option value="MI">MI</option>
								<option value="MN">MN</option>
								<option value="MO">MO</option>
								<option value="MS">MS</option>
								<option value="MT">MT</option>
								<option value="NC">NC</option>
								<option value="ND">ND</option>
								<option value="NE">NE</option>
								<option value="NH">NH</option>
								<option value="NJ">NJ</option>
								<option value="NM">NM</option>
								<option value="NV">NV</option>
								<option value="NY" selected>NY</option>
								<option value="OH">OH</option>
								<option value="OK">OK</option>
								<option value="OR">OR</option>
								<option value="PA">PA</option>
								<option value="RI">RI</option>
								<option value="SC">SC</option>
								<option value="SD">SD</option>
								<option value="TN">TN</option>
								<option value="TX">TX</option>
								<option value="UT">UT</option>
								<option value="VA">VA</option>
								<option value="VT">VT</option>
								<option value="WA">WA</option>
								<option value="WI">WI</option>
								<option value="WV">WV</option>
								<option value="WY">WY</option>
								<option value="AA">AA</option>
								<option value="AE">AE</option>
								<option value="AP">AP</option>
								<option value="AS">AS</option>
								<option value="FM">FM</option>
								<option value="GU">GU</option>
								<option value="MH">MH</option>
								<option value="MP">MP</option>
								<option value="PR">PR</option>
								<option value="PW">PW</option>
								<option value="VI">VI</option>
						</select>
						
						<td>
						
						<td>
					
					</tr>
					<tr>
						<td>zip:
						
						<td><input type="text" id="subscribe_zip_code"
							name="subscribe_zip_code" value="10018">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnListCardsForSubscribe" type="button" name="ok"
							value="list cards">
						
						<td>
						
						<td><input id="btnSubscribe" type="button" name="subscribe"
							value="subscribe">
					
					</tr>
				</table>

				<div id="subscribe_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="subscribe_results" name="subscribe_results"
									rows="10" cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>
		<div id="tabs-9">
			<form id="login_form" name=login_form " action="#">
				<table>
					<div id="login9"></div>
					<tr>
						<td>
						
						<td>username:
						
						<td>
						
						<td><input id="username" type="text" name="username"
							value="jmeah80">
						
						<td>
						
						<td>password:
						
						<td>
						
						<td><input id="password" type="password" name="password"
							value="a1234567">
					
					</tr>
					<tr>
						<td>
						
						<td><input id="btnOK9" type="button" name="ok" value="login">
					
					</tr>
				</table>

				<div id="login_form_results">
					<table>
						<tr>
							<td>Results:
						
						</tr>
						<tr>
							<td><textarea id="login_results" name="login_results" rows="10"
									cols="120">Result will be shown here.</textarea>
						
						</tr>
					</table>
				</div>
		
		</div>

	</div>

	</form>
	</div>



	<script language="JavaScript">
	function generateCC(){
		$('#credit_card_number').val('4242424242424242');
		$('#subscribe_credit_card_number').val('4242424242424242');
		return;
		var cc_number = new Array(16);
		var cc_len = 16;
		var start = 0;
		var rand_number = Math.random();

		//switch(document.store_card_form.credit_card_type.value)
		switch($('#credit_card_type').val())		
        {
			case "Visa":
				cc_number[start++] = 4;
				break;
			case "Discover":
				cc_number[start++] = 6;
				cc_number[start++] = 0;
				cc_number[start++] = 1;
				cc_number[start++] = 1;
				break;
			case "MasterCard":
				cc_number[start++] = 5;
				cc_number[start++] = Math.floor(Math.random() * 5) + 1;
				break;
			case "Amex":
				cc_number[start++] = 3;
				cc_number[start++] = Math.round(Math.random()) ? 7 : 4 ;
				cc_len = 15;
				break;
        }

        for (var i = start; i < (cc_len - 1); i++) {
			cc_number[i] = Math.floor(Math.random() * 10);
        }

		var sum = 0;
		for (var j = 0; j < (cc_len - 1); j++) {
			var digit = cc_number[j];
			if ((j & 1) == (cc_len & 1)) digit *= 2;
			if (digit > 9) digit -= 9;
			sum += digit;
		}

		var check_digit = new Array(0, 9, 8, 7, 6, 5, 4, 3, 2, 1);
		cc_number[cc_len - 1] = check_digit[sum % 10];

		//document.store_card_form.credit_card_number.value = "";
		var cc = "";
		for (var k = 0; k < cc_len; k++) {
			cc += cc_number[k];
		}
		$('#credit_card_number').val(cc);
		$('#subscribe_credit_card_number').val(cc);
}
</script>
	<script language="javascript">
	generateCC();
</script>

</body>
</html>